security:
  encoders:
     FOS\UserBundle\Model\UserInterface: plaintext

  role_hierarchy:
    ROLE_ADMIN:       [ROLE_USER, ROLE_CONSULTANT, ROLE_COMMERCIAL, ROLE_GESTION]
    ROLE_SUPER_ADMIN: ROLE_ADMIN

  providers:
    fos_userbundle:
            id: fos_user.user_provider.username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
        pattern: ^/
        form_login:
            provider: fos_userbundle
            csrf_token_generator: security.csrf.token_manager
            # if you are using Symfony < 2.8, use the following config instead:
            # csrf_provider: form.csrf_provider

        logout:       true
        anonymous:    true

  access_denied_url: /login

  access_control:
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/beneficiaire/ajaxSearch$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, role: ROLE_ADMIN }
    - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/received_mer, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/user/type/admin, role: [ROLE_ADMIN] }
    - { path: ^/user/, role: [ROLE_ADMIN, ROLE_COMMERCIAL, ROLE_GESTION] }
    - { path: ^/admin/, role: ROLE_ADMIN }
    - { path: /, role: IS_AUTHENTICATED_FULLY }
