<?php

namespace Application\PlateformeBundle\Repository;

use Application\PlateformeBundle\Entity\Beneficiaire;
use Doctrine\ORM\Query\ResultSetMappingBuilder;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * BeneficiaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeneficiaireRepository extends \Doctrine\ORM\EntityRepository
{   
    public function getBeneficiaire($page, $nbPerPage)
    {
       $query = $this->createQueryBuilder('b')
            ->orderBy('b.id', 'DESC')
            ->getQuery()
        ;

        $query
          // On définit l'annonce à partir de laquelle commencer la liste
          ->setFirstResult(($page-1) * $nbPerPage)
          // Ainsi que le nombre d'annonce à afficher sur une page
          ->setMaxResults($nbPerPage)
        ;

        // Enfin, on retourne l'objet Paginator correspondant à la requête construite
        // (n'oubliez pas le use correspondant en début de fichier)
        return new Paginator($query, true); 
    }
    
    public function search(Beneficiaire $beneficiaire, $debut, $fin, $idUtilisateur)
    {
        $rsm = new ResultSetMappingBuilder($this->getEntityManager());
        $rsm->addRootEntityFromClassMetadata('Application\PlateformeBundle\Entity\Beneficiaire','b');

        $query = 'SELECT b.* FROM beneficiaire b WHERE 1';
        $params = array();

        if(!is_null($beneficiaire->getNomConso())) {
            $query .= ' AND b.nom_conso = :nomConso';
            $params['nomConso'] = $beneficiaire->getNomConso();
        }

        if(!is_null($beneficiaire->getPrenomConso())) {
            $query .= ' AND b.prenom_conso = :prenomConso';
            $params['prenomConso'] = $beneficiaire->getPrenomConso();
        }

        if(!is_null($beneficiaire->getVille())) {
            $query .= ' AND b.ville_id = :villeId';
            $params['villeId'] = $beneficiaire->getVille()->getId();
        }

        if(!is_null($idUtilisateur)){
            $query .= ' AND b.consultant_id = :consultantId';
            $params['consultantId'] = $idUtilisateur;
        }

        if(!is_null($debut)){
            $query .= ' AND b.date_conf_mer >= :dateDebut';
            $params['dateDebut'] = $debut;
        }

        if(!is_null($fin)){
            $query .= ' AND b.date_conf_mer <= :dateFin';
            $params['dateFin'] = $fin;
        }

        $query .= ' ORDER BY b.id DESC';

        $request = $this->getEntityManager()->createNativeQuery($query,$rsm);
        $request->setParameters($params);

        return $request;
    }
}
