<?php

namespace Application\PlateformeBundle\Repository;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * BureauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BureauRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll() {
        parent::findAll();
        $queryBuilder = $this->createQueryBuilder("b")
                ->leftJoin('b.ville', 'v')
                ->addSelect('v')
				->where('b.supprimer = 0')
                ->orderBy("v.nom", "ASC");
        $query = $queryBuilder->getQuery();
        $results = $query->getResult();
        return $results;
    }
    // Recuperer l'id du bureau par rapport à la ville
    public function retreiveBureau($ville){
        return 
                $this
                    ->createQueryBuilder('b')
                    ->where('b.ville = :ville')
                    ->setParameter('ville',$ville)
                    ->getQuery()
                    ->getResult();
    }

    public function getBureaux($ville){
        $rsm = new ResultSetMappingBuilder($this->getEntityManager());
        $rsm->addRootEntityFromClassMetadata('Application\PlateformeBundle\Entity\Bureau','b');
        $rsm->addJoinedEntityFromClassMetadata('Application\PlateformeBundle\Entity\Ville','v','b');

        $query = 'SELECT b.* FROM bureau b WHERE 1';
        $params = array();

        if(!is_null($ville)) {
            $query .= ' AND b.ville_id = :villeId';
            $params['villeId'] = $ville->getId();
        }

        $request = $this->getEntityManager()->createNativeQuery($query,$rsm);
        $request->setParameters($params);

        return $request;
    }

    public function getBureauByDpt($dpt){
        $queryBuilder = $this->createQueryBuilder('b')
            ->innerJoin('b.ville','v')
            ->where('v.dpt = :dpt')
            ->setParameter('dpt',$dpt)
            ;
        $query = $queryBuilder->getQuery();
        $results = $query->getResult();
        return $results;
    }
}
