<?php

namespace Application\PlateformeBundle\Repository;

/**
 * DetailStatutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailStatutRepository extends \Doctrine\ORM\EntityRepository
{
}
