<?php

namespace Application\PlateformeBundle\Repository;

/**
 * EmployeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeurRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        parent::findAll();
        $queryBuilder = $this->createQueryBuilder("e")
            ->where("e.raisonSociale <> ''")
            ->orderBy("e.raisonSociale", "ASC");
        $query = $queryBuilder->getQuery();
        $results = $query->getResult();
        return $results;
    }
}
