<?php

namespace Application\PlateformeBundle\Repository;

/**
 * EmployeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeurRepository extends \Doctrine\ORM\EntityRepository
{
}
