<?php

namespace Application\PlateformeBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * FactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllFacture($page, $nbPerPage)
    {
        $query = $this->createQueryBuilder('f')
            ->orderBy('f.id', 'DESC')
        ;

        $query->setFirstResult(($page-1) * $nbPerPage)
            ->setMaxResults($nbPerPage);

        // Enfin, on retourne l'objet Paginator correspondant à la requête construite
        // (n'oubliez pas le use correspondant en début de fichier)
        return new Paginator($query);
    }
}
