<?php

namespace Application\PlateformeBundle\Repository;

/**
 * FinanceurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinanceurRepository extends \Doctrine\ORM\EntityRepository
{
}
