<?php

namespace Application\PlateformeBundle\Repository;

/**
 * HistoriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueRepository extends \Doctrine\ORM\EntityRepository
{
    // Historique inferieur à la date du jour
    public function historiquepast($datedujour, $beneficiaireid)
    {
        $ar = 'on';
        return
            $this
                ->createQueryBuilder('h')
                ->where('h.beneficiaire = :benef')
                ->setParameter('benef', $beneficiaireid)
                ->andwhere('h.eventarchive <> :arch')
                ->setParameter('arch', $ar)
                ->orderBy('h.dateDebut', 'DESC')
                ->getQuery()
                ->getResult();
    }

    public function findEventByDate($date)
    {
        $queryBuilder = $this->createQueryBuilder("h")
            ->where("h.dateDebut LIKE :date")
            ->setParameter("date", $date . '%')
            ->andWhere("h.eventarchive != :archive")
            ->setParameter("archive", 'on');
        $query = $queryBuilder->getQuery();
        $results = $query->getResult();
        return $results;
    }

    public function findEventByDateAndConsultant($date, $consultant)
    {
        $queryBuilder = $this->createQueryBuilder("h")
            ->where("h.dateDebut LIKE :date")
            ->andWhere("h.consultant = :consultant")
            ->andWhere("h.eventarchive != :archive")
            ->setParameters(array(
                "date" => $date . '%',
                "consultant" => $consultant,
                "archive" => 'on'
            ))
            ->orderBy("h.heuredebut", "ASC");

        $query = $queryBuilder->getQuery();
        $results = $query->getResult();
        return $results;
    }

    public function getLastRv1orRv2($beneficiaire){
        $queryBuilder = $this->createQueryBuilder("h")
            ->where("h.beneficiaire = :beneficiaire")
            ->andWhere("h.summary = :rv1 OR h.summary = :rv2")
            ->andWhere("h.dateDebut <= :date")
            ->setParameters(array(
                "beneficiaire" => $beneficiaire,
                "rv1" => "RV1",
                "rv2" => "RV2",
                "date" => new \DateTime('now')
            ))
            ->orderBy("h.dateDebut", "DESC")
            ->setMaxResults(1)
        ;

        $query = $queryBuilder->getQuery();
        $results = $query->getResult();
        return $results;
    }

    // Renvoie l'historique d'un beneficiaire données
    public function beneficiaireOne($beneficiaireid){
        $datedujour = new \DateTime('now');
        $ar = 'on';
        return $this
            ->createQueryBuilder('h')
            ->where('h.beneficiaire = :benef')
            ->setParameter('benef',$beneficiaireid)
            ->andWhere('h.dateDebut >= :datedeb')
            ->setParameter('datedeb', $datedujour)
            ->andwhere('h.eventarchive <> :arch')
            ->setParameter('arch',$ar)
            ->getQuery()
            ->getResult();
    }

}
