<?php

namespace Application\PlateformeBundle\Repository;

/**
 * HistoriquePaiementFactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriquePaiementFactureRepository extends \Doctrine\ORM\EntityRepository
{
}
