<?php

namespace Application\PlateformeBundle\Repository;

/**
 * MerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MerRepository extends \Doctrine\ORM\EntityRepository
{
}
