<?php

namespace Application\PlateformeBundle\Repository;

use Application\PlateformeBundle\Entity\Statut;
/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNewsByStatut()
    {
        //RV1 à faire
        $queryBuilder = $this->createQueryBuilder('n')
                ->where('n.statut = :statut')
                ->setParameter('statut', 3)
                ->orderBy("n.id", "DESC");
        
        $query = $queryBuilder->getQuery();
        $results = $query->getResult();
        return $results;
    }
}
