<?php

namespace Application\PlateformeBundle\Repository;

/**
 * NouvelleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NouvelleRepository extends \Doctrine\ORM\EntityRepository
{
}
