<?php

namespace Application\PlateformeBundle\Repository;

/**
 * RessourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RessourceRubriqueRepository extends \Doctrine\ORM\EntityRepository
{
}
