<?php

namespace Application\PlateformeBundle\Repository;

/**
 * StatutRecevabiliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutRecevabiliteRepository extends \Doctrine\ORM\EntityRepository
{
}
