<?php

namespace Application\PlateformeBundle\Repository;

/**
 * SuiviAdministratifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuiviAdministratifRepository extends \Doctrine\ORM\EntityRepository
{
}
