<?php

namespace Application\PlateformeBundle\Repository;

/**
 * SuiviAdministratifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuiviAdministratifRepository extends \Doctrine\ORM\EntityRepository
{
	public function findBeforeDateAndDetailStatut($date, $detailStatut)
	{
		$queryBuilder = $this->createQueryBuilder('s')
                ->where('s.date < :date')
                ->setParameter('date', $date)
				->andWhere('s.detailStatut = :detailStatut')
                ->setParameter('detailStatut', $detailStatut)
                ;
        
        $query = $queryBuilder->getQuery();
        $results = $query->getResult();
        return $results;
	}
	
	public function findByBeneficiaireAndDate($beneficiaire, $date)
	{
		$queryBuilder = $this->createQueryBuilder('s')
                ->where('s.date > :date')
                ->setParameter('date', $date)
				->andWhere('s.beneficiaire = :beneficiaire')
                ->setParameter('beneficiaire', $beneficiaire)
                ;
        
        $query = $queryBuilder->getQuery();
        $results = $query->getResult();
        return $results;
	}
}
