<?php

namespace Application\PlateformeBundle\Repository;

//use Doctrine\ORM\QueryBuilder;

/**
 * VilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VilleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByDepartement($departement)
    {
        $queryBuilder = $this->createQueryBuilder("v")
                ->where("v.cp LIKE :departement")
                ->setParameter("departement", $departement.'%')
                ->orderBy("v.nom", "ASC");
        $query = $queryBuilder->getQuery();
        $results = $query->getResult();
        return $results;
        
    }
}
