application_users_new_document:
    path:     /new/{id}
    defaults: { _controller: "ApplicationUsersBundle:Document:new" }
    options:
        expose:  true

application_users_show_document:
    path: /show/{id}
    defaults: { _controller: "ApplicationUsersBundle:Document:show" }
    options:
        expose:  true