application_new_historique:
    path:     /new/{id}
    defaults: { _controller: "ApplicationPlateformeBundle:Historique:new" }

application_create_historique:
    path:     /create
    defaults: { _controller: "ApplicationPlateformeBundle:Historique:create" }

application_delete_historique:
    path:     /delete/{id}
    defaults: { _controller: "ApplicationPlateformeBundle:Historique:delete" }

application_edit_historique:
    path:     /edit/{id}
    defaults: { _controller: "ApplicationPlateformeBundle:Historique:update" }
