application_category_ressource:
    path:     /rubrique/{id}
    defaults: { _controller: "ApplicationPlateformeBundle:Ressource:index" }
    requirements:
        id: '\d+'

application_delete_ressource:
    path:     /delete/{id}
    defaults: { _controller: "ApplicationPlateformeBundle:Ressource:delete" }

application_update_ressource:
    path:     /update/{id}
    defaults: { _controller: "ApplicationPlateformeBundle:Ressource:edit" }

application_add_ressource:
    path:     /add
    defaults: { _controller: "ApplicationPlateformeBundle:Ressource:add" }

application_index_ressource:
    path:     /rubrique/all
    defaults: { _controller: "ApplicationPlateformeBundle:Ressource:index" }