application_new_suivi_administratif:
    path:     /new/{id}
    defaults: { _controller: "ApplicationPlateformeBundle:SuiviAdministratif:new" }

application_delete_suivi_administratif:
    path:     /delete/{id}
    defaults: { _controller: "ApplicationPlateformeBundle:SuiviAdministratif:delete" }

application_edit_suivi_administratif:
    path:     /update/{id}
    defaults: { _controller: "ApplicationPlateformeBundle:SuiviAdministratif:update" }