<?php

namespace Application\UsersBundle\Repository;

/**
 * DocumentConsultantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentConsultantRepository extends \Doctrine\ORM\EntityRepository
{
}
