<?php

namespace Application\UsersBundle\Repository;

/**
 * MissionArchiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MissionArchiveRepository extends \Doctrine\ORM\EntityRepository
{
}
