<?php

namespace Application\UsersBundle\Repository;

/**
 * StatutConsultantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutConsultantRepository extends \Doctrine\ORM\EntityRepository
{
}
