<?php

namespace Application\UsersBundle\Repository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByTypeUser($slugType)
    {   
        
        $qb = $this->createQueryBuilder('u');

        $qb ->where('u.roles LIKE :type')
            ->setParameter('type', '%'.$slugType.'%');
        ;

        return $qb
          ->getQuery()
          ->getResult()
        ; 
    }
}
